export const data = [
   {
      id: 1,
      price: 28.99,
      name: "Siberian Nutrogunz",
      searchTerm: "protein",
      flavor: 'chocolate',
      image: "./img/data-img/1-chocolate-whey.webp",
   },
   {
      id: 2,
      price: 28.99,
      name: "Siberian Nutrogunz",
      searchTerm: "protein",
      flavor: 'strawberry',
      image: "./img/data-img/2-strawberry-whey.webp",
   },
   {
      id: 3,
      price: 28.99,
      name: "Siberian Nutrogunz",
      searchTerm: "protein",
      flavor: 'banana',
      image: "./img/data-img/3-banana-whey.webp",
   },
   {
      id: 4,
      price: 28.99,
      name: "Siberian Nutrogunz",
      searchTerm: "protein",
      flavor: 'pistachio',
      image: "./img/data-img/4-pistachio-whey.webp",
   },
   {
      id: 5,
      price: 28.99,
      name: "Siberian Nutrogunz",
      searchTerm: "protein",
      flavor: 'lemon tart',
      image: "./img/data-img/5-lemon-tart-whey.webp",
   },
   {
      id: 6,
      price: 28.99,
      name: "Siberian Nutrogunz",
      searchTerm: "protein",
      flavor: 'chocolate cookies',
      image: "./img/data-img/6-chocolate-cookies-whey.webp",
   },
   {
      id: 7,
      price: 35.99,
      name: "MAXLER",
      searchTerm: "protein",
      flavor: 'salted caramel',
      image: "./img/data-img/7-salted-caramel-whey.webp",
   },
   {
      id: 8,
      price: 35.99,
      name: "MAXLER",
      searchTerm: "protein",
      flavor: 'latte macchiato',
      image: "./img/data-img/8-latte-macchiato-whey.webp",
   },
   {
      id: 9,
      price: 35.99,
      name: "MAXLER",
      searchTerm: "protein",
      flavor: 'milk chocolate',
      image: "./img/data-img/9-milk-chocolate-whey.webp",
   },
   {
      id: 10,
      price: 35.99,
      name: "MAXLER",
      searchTerm: "protein",
      flavor: 'milkshake with strawberries',
      image: "./img/data-img/10-milkshake-with-strawberries-whey.webp",
   },
   {
      id: 11,
      price: 35.99,
      name: "MAXLER",
      searchTerm: "protein",
      flavor: 'chocolate with coconut chips',
      image: "./img/data-img/11-chocolate-with-coconut-chips-whey.webp",
   },
   {
      id: 12,
      price: 35.99,
      name: "MAXLER",
      searchTerm: "protein",
      flavor: 'vanilla ice cream',
      image: "./img/data-img/12-vanilla-ice-cream-whey.webp",
   },
   // ==========================================================================
   {
      id: 13,
      price: 35.99,
      name: "Optimum Nutrition",
      searchTerm: "creatine",
      flavor: 'monohydrate',
      image: "./img/data-img/13-on-creatine.webp",
   },
   {
      id: 14,
      price: 31.99,
      name: "MAXLER",
      searchTerm: "creatine",
      flavor: 'monohydrate',
      image: "./img/data-img/14-maxler-creatine.webp",
   },
   {
      id: 15,
      price: 27.99,
      name: "Siberian Nutrogunz",
      searchTerm: "creatine",
      flavor: 'strawberry',
      image: "./img/data-img/15-sn-strawberry-creatine.webp",
   },
   {
      id: 16,
      price: 27.99,
      name: "Siberian Nutrogunz",
      searchTerm: "creatine",
      flavor: 'exotics',
      image: "./img/data-img/16-sn-exotics-creatine.webp",
   },
   // ==========================================================================
   {
      id: 17,
      price: 20.99,
      name: "MAXLER",
      searchTerm: "gainer",
      flavor: 'chocolate',
      image: "./img/data-img/17-maxler-chocolate-gainer.webp",
   },
   {
      id: 18,
      price: 20.99,
      name: "MAXLER",
      searchTerm: "gainer",
      flavor: 'vanilla',
      image: "./img/data-img/18-maxler-vanilla-gainer.webp",
   },
   {
      id: 19,
      price: 20.99,
      name: "Siberian Nutrogunz",
      searchTerm: "gainer",
      flavor: 'strawberry',
      image: "./img/data-img/19-sn-strawberry-gainer.webp",
   },
   {
      id: 20,
      price: 20.99,
      name: "Siberian Nutrogunz",
      searchTerm: "gainer",
      flavor: 'banana',
      image: "./img/data-img/20-sn-banana-gainer.webp",
   },
   {
      id: 21,
      price: 20.99,
      name: "Siberian Nutrogunz",
      searchTerm: "gainer",
      flavor: 'vanilla ice cream',
      image: "./img/data-img/21-sn-vanilla-ice-cream-gainer.webp",
   },
   {
      id: 22,
      price: 20.99,
      name: "Siberian Nutrogunz",
      searchTerm: "gainer",
      flavor: 'pecan cookies',
      image: "./img/data-img/22-sn-pecan-cookies-gainer.webp",
   },
   // ==========================================================================
   // {
   //    id: 23,
   //    price: ,
   //    name: "",
   //    searchTerm: "",
   //    flavor: '',
   //    image: "./img/data-img",
   // },
   // {
   //    id: 24,
   //    price: ,
   //    name: "",
   //    searchTerm: "",
   //    flavor: '',
   //    image: "./img/data-img",
   // },
   // {
   //    id: 25,
   //    price: ,
   //    name: "",
   //    searchTerm: "",
   //    flavor: '',
   //    image: "./img/data-img",
   // },
   // {
   //    id: 26,
   //    price: ,
   //    name: "",
   //    searchTerm: "",
   //    flavor: '',
   //    image: "./img/data-img",
   // },
   // {
   //    id: 27,
   //    price: ,
   //    name: "",
   //    searchTerm: "",
   //    flavor: '',
   //    image: "./img/data-img",
   // },
   // {
   //    id: 28,
   //    price: ,
   //    name: "",
   //    searchTerm: "",
   //    flavor: '',
   //    image: "./img/data-img",
   // },
   // {
   //    id: 29,
   //    price: ,
   //    name: "",
   //    searchTerm: "",
   //    flavor: '',
   //    image: "./img/data-img",
   // },
   // {
   //    id: 30,
   //    price: ,
   //    name: "",
   //    searchTerm: "",
   //    flavor: '',
   //    image: "./img/data-img",
   // },
]

